version: '3'
services:
  server:
    image: "johnyjd/multi-server"
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PG_USER=$PGUSER
      - PG_PASSWORD=$PGPASSWORD
      - PG_HOST=$PGHOST
      - PG_PORT=$PGPORT
      - PG_DATABASE=$PGDATABASE
      - PORT=5000
  worker:
    image: "johnyjd/multi-worker"
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    hostname: worker
  client:
    image: "johnyjd/multi-client"
    environment:
      - WDS_SOCKET_PORT=0
    hostname: client
  nginx:
    image: "johnyjd/multi-nginx"
    restart: always
    hostname: nginx
    ports: 
      - '80:80'
