name: Deploy Multidocker
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Building testing container
          run: docker build -t johnyjd/client-test -f ./client/Dockerfile.dev ./client
        
        - name: Testing
          run: docker run -e CI=true johnyjd/client-test npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - run: docker build -t johnyjd/multi-client ./client
      - run: docker build -t johnyjd/multi-nginx ./nginx
      - run: docker build -t johnyjd/multi-server ./server
      - run: docker build -t johnyjd/multi-worker ./worker

      - run: docker push johnyjd/multi-client
      - run: docker push johnyjd/multi-nginx
      - run: docker push johnyjd/multi-server
      - run: docker push johnyjd/multi-worker
      
  deploy:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Creating bundle
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to AWS
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: ${{ env.AWS_APP_NAME }}
          environment_name: ${{ env.AWS_APP_NAME }}
          existing_bucket_name: elaselasticbeanstalk-eu-north-1-322209956507
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
